### ISSUE TITLE
mm2: Add overlay in Inspector window has entry org.micromanager.patternoverly.PatternOverlay.java

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#92] opened 2015-11-05 23:19 UTC
Most people will not know what that means, or if they do, it look ugly.  Can this be changed to "PatternOverlay"?

**Comment by ChrisWeisiger** [comment] 2015-11-06 17:32
This was a bug caused by a change in how we were storing plugins internally. It's been fixed now. Thanks for the report!

**Closed by ChrisWeisiger** 2015-11-06 17:32 UTC
