### ISSUE TITLE
java error: Load MMCoreJ_wrap: Try loading: /usr/local/ImageJ/libMMCoreJ_wrap.so

### ISSUE THREAD

**Issue by misalvat** [micro-manager/micro-manager#21] opened 2015-03-06 14:12 UTC
Hi, 

I installed micro-manager1.4, when I run the software by the following command I got this error:

Load MMCoreJ_wrap: Will search in hard-coded paths:
Load MMCoreJ_wrap:   /usr/local/ImageJ/plugins/Micro-Manager
Load MMCoreJ_wrap:   /usr/local/ImageJ/plugins
Load MMCoreJ_wrap:   /usr/local/ImageJ/plugins/mm/linux64
Load MMCoreJ_wrap:   /usr/local/ImageJ
Load MMCoreJ_wrap:   /usr/local/ImageJ/mm/linux64
Load MMCoreJ_wrap:   /usr/local/lib/micro-manager
Load MMCoreJ_wrap: Skipping nonexistent candidate: /usr/local/ImageJ/plugins/Micro-Manager/libMMCoreJ_wrap.so
Load MMCoreJ_wrap: Skipping nonexistent candidate: /usr/local/ImageJ/plugins/libMMCoreJ_wrap.so
Load MMCoreJ_wrap: Skipping nonexistent candidate: /usr/local/ImageJ/plugins/mm/linux64/libMMCoreJ_wrap.so
Load MMCoreJ_wrap: Try loading: /usr/local/ImageJ/libMMCoreJ_wrap.so

![screenshot from 2015-03-06 15 10 25](https://cloud.githubusercontent.com/assets/5747846/6526518/ff596278-c412-11e4-931b-d44504841da0.png)

I'm using javac 1.7.0_76 java version...

thanks.

Michele

**Comment by marktsuchida** [comment] 2015-03-16 22:35
Most likely a build configuration issue, not a bug. Please ask on the mailing list if you need help resolving build issues.

**Closed by marktsuchida** 2015-03-16 22:35 UTC
