### ISSUE TITLE
mm2: Error in Inspector window when opening the first file using Open Recent menu

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#113] opened 2015-11-25 20:01 UTC
After starting mm2 and opening a file using the Open Recent (RAM) menu entry, there is an exception in the histogram code:
2015-11-25T11:56:19.528551 tid0x17b71a000 [IFO,App] Error: No display settings found at /Volumes/nstuurman/Images/2014/20140915-BangaloreCourse/BPAECells2
2015-11-25T11:56:20.362165 tid0x17b71a000 [IFO,App] Error receiving new histograms
                                          [       ] java.lang.NullPointerException in Thread[Thread-3,6,main]
                                          [       ]   at org.micromanager.display.internal.inspector.ChannelControlPanel.updateHistogram(ChannelControlPanel.java:864)
                                          [       ]   at org.micromanager.display.internal.inspector.ChannelControlPanel.redraw(ChannelControlPanel.java:891)
                                          [       ]   at org.micromanager.display.internal.inspector.ChannelControlPanel.reloadDisplaySettings(ChannelControlPanel.java:664)
                                          [       ]   at org.micromanager.display.internal.inspector.ChannelControlPanel.initialize(ChannelControlPanel.java:168)
                                          [       ]   at org.micromanager.display.internal.inspector.ChannelControlPanel.onNewHistograms(ChannelControlPanel.java:778)
                                          [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
The Inspector window looks really weird: 

![clipboard](https://cloud.githubusercontent.com/assets/2153771/11408119/05f93616-936c-11e5-8d2b-8ff9c8b60146.png)

This only happens with the very first file that I open and only using the "Open Recent" menu.  It happens with the two files that I tested (including the BPAECells2 file)

**Comment by ChrisWeisiger** [comment] 2015-11-30 21:38
Thanks for the report. This turned out to be caused by the recent refactoring that created the DataViewer setup and de-coupled the histograms from the DisplayWindow. It should be fixed now; please re-open if you continue to see problems.

**Closed by ChrisWeisiger** 2015-11-30 21:38 UTC
