### ISSUE TITLE
mm2: Acquisition comments lost?

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#141] opened 2016-01-08 23:09 UTC
Run an MDA with a comment entered in the MDA dialog. The comment does not show up in the Inspector's Comments section.
(It seems to also not be saved in the file.)

**Comment by ChrisWeisiger** [comment] 2016-01-08 23:34
This is caused by the Clojure acquisition engine storing the summary metadata comment under "Comment", while MDUtils looks for the comment under "Comments".

**Comment by marktsuchida** [comment] 2016-01-09 00:43
Which might mean that comments have always been broken in the mm2 branch, since MDUtils in 1.4 did not have a method for Comment(s). In 1.4 the summary metadata key was "Comment", not "Comments"; we should keep it that way.
See also: #143.

**Comment by ChrisWeisiger** [comment] 2016-01-11 21:20
This is now fixed.

**Closed by ChrisWeisiger** 2016-01-11 21:20 UTC
