### ISSUE TITLE
Display hangs

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#411] opened 2016-08-18 18:17 UTC
The time point (or other) scroll bars stop working. Not easy to reproduce, but can happen semi-repeatably on a given system with given settings.

Example stack trace (seen with a dual camera MDA, time series, zero interval, single channel selected):

```
2016-08-18T17:48:43.601704 tid5224 [IFO,App] Failed to respond to datastore saved event
                                   [       ] java.lang.NullPointerException in Thread[TaggedImage sink thread,6,main]
                                   [       ]   at ij.CompositeImage.updateImage(CompositeImage.java:293)
                                   [       ]   at org.micromanager.display.internal.MMCompositeImage.superUpdateImage(MMCompositeImage.java:155)
                                   [       ]   at org.micromanager.display.internal.MMCompositeImage.updateAndDraw(MMCompositeImage.java:175)
                                   [       ]   at ij.ImagePlus.setStack(ImagePlus.java:654)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.resetTitle(DefaultDisplayWindow.java:526)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.onDatastoreFrozen(DefaultDisplayWindow.java:1167)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                                   [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                                   [       ]   at java.lang.reflect.Method.invoke(Unknown Source)
                                   [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                   [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                   [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                   [       ]   at org.micromanager.internal.utils.PrioritizedEventBus.post(PrioritizedEventBus.java:64)
                                   [       ]   at org.micromanager.data.internal.DefaultDatastore.freeze(DefaultDatastore.java:306)
                                   [       ]   at org.micromanager.acquisition.internal.MMAcquisition.onAcquisitionEnded(MMAcquisition.java:367)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                                   [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                                   [       ]   at java.lang.reflect.Method.invoke(Unknown Source)
                                   [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                   [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                   [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                   [       ]   at org.micromanager.events.internal.DefaultEventManager.post(DefaultEventManager.java:33)
                                   [       ]   at org.micromanager.acquisition.internal.DefaultTaggedImageSink$1.run(DefaultTaggedImageSink.java:62)
```

Even if this turns out to be an ImageJ quirk, we should be able to work around it.

**Comment by nicost** [comment] 2020-04-04 18:25
The code has been refactored drastically since this issue was opened.  Closing for now (not pretending issues like this can not happen anymore, but it will be more fruitful to open new tickets when the problem re-occurs and can be reproduced).

**Closed by nicost** 2020-04-04 18:25 UTC
Labels: bug, mm2
